pipeline:
  alpine:
    image: alpine:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk update && apk add make docker
      - cd $DRONE_WORKSPACE
      - make build
      - make test
      - make test-official-bats || echo "Failure in official repo ($?)"
  debian:
    image: debian:latest
    commands:
      - apt-get update && apt-get install -qqy make docker
      - cd $DRONE_WORKSPACE
      - make build
      - make test
      - make test-official-bats || echo "Failure in official repo ($?)"
