pipeline:
  shell:
    image: docker
    commands:
     - apt-get install make
     - cd $DRONE_WORKSPACE
     - make build
     - make test
     - make test-official-bats || echo "Failure in official repo ($?)"
