pipeline:
  ubuntu:
    image: dotmpe/ubuntu-docker:xenial
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --version
      - apt-get update && apt-get install make
      - cd $DRONE_WORKSPACE
      - make
      - cd ubuntu-bats/xenial
      - docker build --build-arg X_DCKR_BASENAME=ubuntu-bats -t ubuntu-bats:xenial .
    when:
      branch: master
  debian:
    image: dotmpe/debian-docker:unstable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --version
      - apt-get update && apt-get install make
      - cd $DRONE_WORKSPACE
      - make
      - cd debian-bats/unstable
      # FIXME: newer dockers don't like build-args in FROM
      #- docker build --build-arg X_DCKR_BASENAME=debian-bats -t debian-bats:unstable .
    when:
      branch: master
  alpine:
    image: dotmpe/alpine-docker:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --version
      - apk update && apk add make
      - cd $DRONE_WORKSPACE
      - make
      # FIXME: can't reproduce dev build setup in Drone DinD
      #- make build:alpine-bats
        #- make build
        #- make test
        #- make test-official-bats || echo "Failure in official repo ($?)"
      #- cd alpine-bats/edge
      #- docker build --build-arg X_DCKR_BASENAME=alpine-bats -t alpine-bats:edge .
    when:
      branch: master
  xenial-git-annex:
    image: ubuntu:xenial
    commands:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get -qyy install git-annex
      - mkdir /tmp/annex && cd /tmp/annex
      - git init
      - git annex init
    when:
      branch: master
