pipeline:
  alpine:
    image: alpine:edge
    commands:
     - apk update && apk add make
     - cd $DRONE_WORKSPACE
     - make build
     - make test
     - make test-official-bats || echo "Failure in official repo ($?)"
  debian:
    image: debian:latest
    commands:
     - apt-get update &7 apt-get install -qqy make
     - cd $DRONE_WORKSPACE
     - make build
     - make test
     - make test-official-bats || echo "Failure in official repo ($?)"
