pipeline:
  ubuntu:
    image: bvberkum/ubuntu-docker:xenial
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --version
      - apt-get update && apt-get install make
      - cd $DRONE_WORKSPACE
      - make
      #- make build:alpine-bats
        #- make build
        #- make test
        #- make test-official-bats || echo "Failure in official repo ($?)"
      - cd alpine-bats/edge
      - docker --version
      #- docker build --build-arg X_DCKR_BASENAME=alpine-bats -t alpine-bats:edge .
      # FIXME: can't reproduce dev build setup in Drone DinD
    when:
      branch: master
  alpine:
    image: bvberkum/alpine-docker:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker --version
      - apk update && apk add make
      - cd $DRONE_WORKSPACE
      - make
      #- make build:alpine-bats
        #- make build
        #- make test
        #- make test-official-bats || echo "Failure in official repo ($?)"
      - cd alpine-bats/edge
      - docker build --build-arg X_DCKR_BASENAME=alpine-bats -t alpine-bats:edge .
      # FIXME: can't reproduce dev build setup in Drone DinD
    when:
      branch: master
  xenial-git-annex:
    image: ubuntu:xenial
    commands:
      - apt-get update
      - apt-get install git-annex
      - mkdir /tmp/annex && cd /tmp/annex
      - git init
      - git annex init
    when:
      branch: master
