
- type: application/vnd.org.wtwta.project
  id: dotmpe/x-docker

  scripts:
    init:
      - htd package update
      - htd package remotes-reset
      - vc regenerate
      - test -e .git/hooks/pre-commit || ln -s ../../tools/git-hooks/pre-commit .git/hooks/pre-commit
    build-treebox:
      - cd ubuntu-treebox/xenial;
        docker build \
          --build-arg X_DCKR_PREFIX=dotmpe \
          --build-arg X_DCKR_BASENAME=ubuntu-treebox \
          --build-arg X_DCKR_NAME=dotmpe/ubuntu-treebox \
          --build-arg X_DCKR_TAG=xenial \
          -t ubuntu-treebox:xenial .

  repositories:
    notus.24-2: /srv/scm-git-24-2-notus-brix/dotmpe/x-docker.git
    dandy.9-1: /srv/scm-git-9-1-dandy-mpe/dotmpe/x-docker.git
    dotmpe.origin: domains/dotmpe.com/htdocs/git/x-docker.git
    github: git@github.com:dotmpe/x-docker.git


- type: application/vnd.org.wtwta.environment
  id: dotmpe/x-docker-main
  main: dotmpe/x-docker

