
- type: application/vnd.org.wtwta.project
  id: bvberkum/x-docker
  repositories:
    boreas.16-4: /srv/scm-git-16-4-boreas-brix/bvberkum/x-docker.git
    dandy.9-1: /srv/scm-git-9-1-dandy-mpe/bvberkum/x-docker.git

  scripts:
    init:
      - htd package update
      - htd package remotes-reset
      - vc regenerate
    build-treebox:
      - cd ubuntu-treebox/xenial;
        docker build \
          --build-arg X_DCKR_PREFIX=bvberkum \
          --build-arg X_DCKR_BASENAME=ubuntu-treebox \
          --build-arg X_DCKR_NAME=bvberkum/ubuntu-treebox \
          --build-arg X_DCKR_TAG=xenial \
          -t ubuntu-treebox:xenial .

- type: application/vnd.org.wtwta.environment
  id: bvberkum/x-docker-main
  main: bvberkum/x-docker

